package stratum.cli

import stratum.canon.Canon

/**
 * The frozen host core interface.
 *
 * This manifest is the semantic identity of the bootstrap host: the canonical
 * value tags, the artifact envelope, the fixed Meta0 forms and primitive set,
 * the fixed Grammar0 forms, the evidence shape and the verdict forms.
 *
 * Every foundation from F1 onward references exactly this identity. Adding a
 * primitive, an expression form, a pattern form or a grammar form changes the
 * digest and therefore has to be a deliberate, reviewed act.
 *
 * Capability adapters are deliberately excluded: the freeze permits new
 * adapters, additional host implementations and diagnostics that do not affect
 * canonical verdicts.
 */
object HostCore:

  val header: String =
    "; Generated by `stratum host manifest`. Do not edit by hand.\n" +
      "; This is the frozen host core identity referenced by every foundation.\n"

  private def symbols(names: Seq[String]): Canon = Canon.L(names.map(Canon.Sym.apply).toVector)

  val canonTags: Vector[String] =
    Vector("unit", "bool", "nat", "int", "bytes", "string", "symbol", "reference", "list", "map", "node")

  val expressionForms: Vector[String] =
    Vector("q", "v", "mk", "lst", "mp", "if", "let", "call", "match", "prim", "cap", "fail")

  val patternForms: Vector[String] =
    Vector("_", "pv", "pq", "pm", "pnode", "pl", "pcons", "pnil")

  val primitives: Vector[String] = Vector(
    "add", "and", "append", "args", "bcat", "blen", "cmp", "cons", "contains", "decode", "digest",
    "distinct", "div", "drop", "encode", "eq", "ge", "gt", "head", "index-of", "insert-at", "is-bool",
    "is-bytes", "is-int", "is-list", "is-map", "is-nat", "is-node", "is-ref", "is-str", "is-sym",
    "is-unit", "le", "len", "lt", "max", "mdel", "mentries", "mfrom", "mget", "mhas", "min", "mkeys",
    "mnew", "mod", "mput", "msize", "mul", "mvals", "nat->str", "ne", "nil?", "node", "not", "nth",
    "or", "prim-free", "remove-at", "rev", "scat", "set-nth", "slen", "snoc", "sort", "ssub",
    "str->nat", "str->sym", "sub", "sym->str", "tag", "tail", "take", "ref->str"
  ).filterNot(_ == "prim-free").sorted

  val grammarDeclarations: Vector[String] = Vector("name", "start", "token", "skip", "category")
  val grammarProductions: Vector[String] = Vector("prod", "pass", "fold", "paren")
  val grammarElements: Vector[String] = Vector("kw", "bind")
  val tokenKinds: Vector[String] = Vector("sym", "str", "nat")
  val evidenceFields: Vector[String] = Vector("steps", "calls", "capabilities")
  val verdictForms: Vector[String] = Vector("ok", "error")

  val manifest: Canon = Canon.node(
    "host-core",
    Canon.node("bootstrap", Canon.S("StratumHost0/1")),
    Canon.node("canon", Canon.node("tags", symbols(canonTags)), Canon.node("identity", Canon.Sym("sha-256"))),
    Canon.node("artifact", Canon.node("envelope", symbols(Vector("kind", "body")))),
    Canon.node(
      "meta0",
      Canon.node("expressions", symbols(expressionForms)),
      Canon.node("patterns", symbols(patternForms)),
      Canon.node("primitives", symbols(primitives))
    ),
    Canon.node(
      "grammar0",
      Canon.node("declarations", symbols(grammarDeclarations)),
      Canon.node("productions", symbols(grammarProductions)),
      Canon.node("elements", symbols(grammarElements)),
      Canon.node("token-kinds", symbols(tokenKinds))
    ),
    Canon.node("evidence", Canon.node("fields", symbols(evidenceFields))),
    Canon.node("verdict", Canon.node("forms", symbols(verdictForms)))
  )
